### ISSUE TITLE
How to train BoxVIS on OVIS only?

### ISSUE THREAD

**Issue by wenhe-jia** [MinghanLi/BoxVIS#2]
I want to train a BoxVIS model only with OVIS dataset, and I think the following params in yaml file should be adjusted as below:

```
    DATASETS:
        DATASET_RATIO: []
        TRAIN: ("ovis_train_org",),   # registered in the **buildin** file of original OVIS train subset
        TEST: ("ovis_val", )
    SEM_SEG_HEAD:
        NUM_CLASSES: 25
    MODEL:
        BoxVIS:
            BVISD_ENABLED: False
```

Are there any other config modifications I should adopt? Thanks for answering.
